source 'https://rubygems.org'

gem 'rails', '~> 3.2'

gem 'email_validator'
gem 'jbuilder'
gem 'pg'
gem 'rack-cors', require: 'rack/cors'
gem 'rails-i18n', '~> 3.0.0'

group :development, :test do
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'rspec-rails'
  gem 'test-unit'
end

group :test do
  gem 'shoulda-matchers'
end
